export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_MOVIES: 'FETCH_MOVIES',
    FETCH_MOVIE: 'FETCH_MOVIE',
    SET_MOVIE: 'SET_MOVIE',
    SET_ACTOR: 'SET_ACTOR',
    FETCH_REVIEWS: 'FETCH_REVIEWS',
    FETCH_MOVIE_ROLES: 'FETCH_MOVIE_ROLES',
    FETCH_ACTOR_ROLES: 'FETCH_ACTOR_ROLES',
    FETCH_ACTORS: 'FETCH_ACTORS',
    FETCH_ACTOR : 'FETCH ACTOR',
    FETCH_WATCHLIST : 'FETCH_WATCHLIST'
}
